### ISSUE TITLE
Move the Javascript code from HTML to .js file.

### ISSUE THREAD

**Issue by KendallDoesCoding** [KendallDoesCoding/random#1]
Currently, the Javascript is in the HTML, I require it to be in a JS file and that JS file to be linked via script:src in the HTML.

**Comment by faiz-ali-khan-developer** [comment]
Hey can you assign me this issue ?

**Comment by KendallDoesCoding** [comment]
Sure. You can work on this. Will assign you when I'm on my laptop.

**Comment by faiz-ali-khan-developer** [comment]
Thanks @KendallDoesCoding I'll start working on this 😊

**Comment by MohsinMalik2** [comment]
Hey Kendall, I'm new to open source and really want to start my journey with this opportunity. Do let me know if you can assign me to this.

**Comment by KendallDoesCoding** [comment]
> Hey Kendall, I'm new to open source and really want to start my journey with this opportunity. Do let me know if you can assign me to this.

Hi @MohsinMalik2 , I can assign you if @fk00750 is okay with it, he asked to work on this before you!, but you can check out my other issues which you can help me with here: https://finder.eddiehub.io/?global=true. Thanks

**Comment by MohsinMalik2** [comment]
Sure. Thank you and do let me know if @fk00750 need any assistance.

**Comment by faiz-ali-khan-developer** [comment]
Hey @KendallDoesCoding I've already fix the issue and if @MohsinMalik2 wants, we can work together on a different issue

**Comment by KendallDoesCoding** [comment]
> Hey @KendallDoesCoding I've already fix the issue and if @MohsinMalik2 wants, we can work together on a different issue

👍 , you forgot to link the PR to the issue.

**Comment by MohsinMalik2** [comment]
@fk00750 I would love to collaborate.

**Comment by faiz-ali-khan-developer** [comment]
@KendallDoesCoding oh my mistake 😅, I'll keep that in mind...

**Comment by faiz-ali-khan-developer** [comment]
hey, @MohsinMalik2 we can work together on this issue [[DOCS] Write comments #299](https://github.com/KendallDoesCoding/mogul-christmas/issues/299). It is not that difficult, you have to test everything and write comments about them...
If you find this worth your time then let me know

**Comment by KendallDoesCoding** [comment]
> hey, @MohsinMalik2 we can work together on this issue [[DOCS] Write comments #299](https://github.com/KendallDoesCoding/mogul-christmas/issues/299). It is not that difficult, you have to test everything and write comments about them... If you find this worth your time then let me know

@MohsinMalik2 if you would like to work on this issue, please comment here and in that issue so I can assign you and @fk00750 accordingly.
